### ISSUE TITLE
runes2 esm 产物没有正确 export default 导致报错

### ISSUE THREAD

**Issue by smithyj** [bluelovers/ws-string#2]
https://github.com/ant-design/ant-design-mobile/issues/6671

45.js:425 Uncaught (in promise)
TypeError: (0 , _runes.default) is not a function

**Comment by bluelovers** [comment]
![image](https://github.com/bluelovers/ws-string/assets/167966/1c2e3eca-89a5-41c7-a6bf-b08c22a70198)

https://github.com/bluelovers/ws-string/blob/929b82744fa31b4a565535d5d0835231d689e378/packages/runes2/dist/index.esm.mjs#L93

**Comment by bluelovers** [comment]
```
import runes from 'runes2'

console.dir(runes('sssss'))
```

我不管是用 tsx 還是 ts-node 跑 .ts 都正常
然後 用 node 跑 .mjs 也是正常

問題可能出在打包程序上

![image](https://github.com/bluelovers/ws-string/assets/167966/f8406431-1706-4eb0-a22d-cadbf3e3325b)

**Comment by smithyj** [comment]
解决了，项目中 webpack 不支持 mjs 后缀，应该要生成 .js 产物
